/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'artem_shevtsov' at '6/22/16 1:20 PM' with Gradle 2.13
 *
 * @author artem_shevtsov, @date 6/22/16 1:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
